language: python
python:
- 2.7
- 3.4
- 3.5
- 3.6

sudo: false

env:
  global:
    - MASTER_BRANCH=master

addons:
  apt:
    packages:
      - gcc
      - gfortran
      - libopenmpi-dev
      - libmumps-seq-dev
      - libblas-dev
      - liblapack-dev

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh
    -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-3.8.3-Linux-x86_64.sh
    -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:/home/travis/miniconda/bin:/home/travis/miniconda/bin:/home/travis/miniconda3/bin:$PATH
  - conda update --yes conda

install:
  - conda install --yes pip python=$TRAVIS_PYTHON_VERSION numpy scipy nose cython
  - pip install nose-cov python-coveralls pyMKL
  - git clone https://github.com/simpeg/discretize.git; cd discretize; python setup.py
    install; cd ..;
  - python setup.py build_ext --inplace
  - make mumps

script:
  - nosetests --with-cov --cov pymatsolver --cov-config .coveragerc -v -s

after_success:
  - bash <(curl -s https://codecov.io/bash)

  - if ! [ "$TRAVIS_BRANCH" = "$MASTER_BRANCH" -o "$TRAVIS_TAG" = "true" ]; then
      echo "Not deploying (because this is not a deployment branch)" ;
      exit 0 ;
    fi

  # unpack credentials
  - openssl aes-256-cbc -K $encrypted_09d25a681e70_key -iv $encrypted_09d25a681e70_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
  - tar -xvzf credentials.tar.gz

  # deploy to pypi on tags
  - mv credentials/.pypirc ~/.pypirc ;
  - python setup.py sdist bdist_wheel --universal upload;

notifications:
  slack: simpeg:1KZq5giMtlJJ58TijIPgqf7n
