os: linux
dist: bionic
language: python
python:
- 3.6
- 3.7
- 3.8
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -bfp ${HOME}/miniconda
  - rm miniconda.sh
  - export PATH=${HOME}/miniconda/bin:$PATH
  - source "$HOME"/miniconda/etc/profile.d/conda.sh
  - conda config --append channels conda-forge
  - conda config --set always_yes yes --set changeps1 no --set auto_update_conda false --set notify_outdated_conda false
install:
  - conda install --yes pip python=$TRAVIS_PYTHON_VERSION pymkl nose nose-cov python-coveralls 
    numpy scipy cython mumps-seq compilers openmpi make curl
  - conda activate
  - pip install "https://github.com/simpeg/discretize/archive/master.zip"
  - conda info -a
  - python setup.py build_ext --inplace
  - make mumps
script:
  - conda activate
  - nosetests --with-cov --cov pymatsolver --cov-config .coveragerc -v -s
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  slack: simpeg:1KZq5giMtlJJ58TijIPgqf7n
